name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.9]
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y expect # Install expect
      - name: Run Pylint
        run: |
          pip install pylint
          pylint ragnews.py
      - name: Run doctests
        run: |
          chmod +x run_doctests.sh
          ./run_doctests.sh
      - name: Test functionality
        run: echo 'spawn python3 ragnews.py; expect "ragnews> "; send "Sample input\r"; interact' | expect